### PR TITLE
Upgrade to SqlClient 5.1.0 with DateOnly/TimeOnly support

### PR DESCRIPTION
**Pull request by SergeiPavlov**
SqlClient 5.1.0 has support of `DateOnly/TimeOnly` types
No need for intermediate conversion

### CODE REVIEW

**Comment by alex-kulakov** [comment]
If you update a storage-specific thing, don't change base implementation, change and override the provider, changing the base one can break and probably will break other providers.

**Comment by alex-kulakov** [comment]
I'm going to publish an RC version of 7.1 with DateOnly/TimeOnly support across all supported types of storages (PR #307). This PR fits it too. But with exception of these two no merges will happen before RC.

**Comment by SergeiPavlov** [comment]
> If you update a storage-specific thing, don't change base implementation, change and override in the the provider, changing the base one can break and probably will break other providers.

Fixed

**Comment by alex-kulakov** [comment]
Also, for the future, ```TypeMapper``` has clear structure of grouped methods, It would be appreciated if ReadXxx, BindXxx and MapXxx methods were added in their groups. It would smooth review process and give you extra points of karma 😉

**Review by alex-kulakov — APPROVED** [review]

**Pull request merged**
