### PR TITLE
Optimizing refactoring: avoid string/TextNode allocations in Sql compiler

### PR DESCRIPTION
**Pull request by SergeiPavlov**
* Use StringBuilder instead of mass string/TextNode allocations

* Optimize Compressor to avoid string copying From TextNodes to other TextNodes. We can postpone concatenation until PostProcessing.

* Remove field `Node.Next`, use `List<Node>` instead

* Refactoring to modern C# syntax
* Optimized `AppendHexArray()`

### CODE REVIEW

**Comment by alex-kulakov** [comment]
@SergeiPavlov, merge of changes from master had broken the build.

**Comment by SergeiPavlov** [comment]
> @SergeiPavlov, merge of changes from master had broken the build.

Fixed it

**Review by alex-kulakov — APPROVED** [review]

**Comment by alex-kulakov** [comment]
I opened a new branch to merge this PR, there ```SqTranslator```s will be changed to this optimized way of work.
Also, @SergeiPavlov can you resolve conflicts with target branch (notice it has been changed) before I merge it?

**Comment by SergeiPavlov** [comment]
conflicts are resolved

**Comment by alex-kulakov** [comment]
Nice! Thank you.

**Pull request merged**
