### PR TITLE
Net standard 21

### PR DESCRIPTION
**Pull request by AlexUstinov**
This PR makes project .Net Standard 2.1 compatible.
This is a move towards the suggested migration to .Net Core 3.1 (See https://github.com/DataObjects-NET/dataobjects-net/issues/11).

### CODE REVIEW

**Comment by alex-kulakov** [comment]
The PR contains a lot of changes which are not relevant to .NET Standard 2.1 migration - a lot of summaries for classes, changes of ```SqlExtactor``` API, a test for FastLambdaExpressions and so on. Is there any explanation why are they here?

I assume migration to .NET Standard should contain changes of target framework for projects and some changes for code migration if needed.

**Review by alex-kulakov — CHANGES_REQUESTED** [review]

**Comment by alex-kulakov** [comment]
Doesn't build at all. FastExpression.cs has two methods with same declaration. Maybe bad merge happened?

**Comment by alex-kulakov** [comment]
Yep, bad merge. Commit a8056d21379f0a30e5c9bdec28d4033d7f2e9341

**Comment by AlexUstinov** [comment]
We'll go forward with .Net Core 3.1 (See #58).

**Pull request closed without merging**
